### ISSUE TITLE
Card doesn't support new weather entitles without forecast attributes

### ISSUE THREAD

**Issue by Scoop2389** [Makin-Things/platinum-weather-card#102]
**Additional Information:**
@Makin-Things, look I'm sorry. I didn't mean to come off as rude or disrespectful to you or anyone who contributed to your project. I was trying to do my due diligence by requesting a card I thought was broken and unmaintained to be removed from HACS. I thought that all weather integrations were updated to this new standard, and that meant that this card would be broken for everyone. I didn't realize that a lot of use cases and weather integrations haven't been updated yet and I didn't know what that request meant to you guys. I really do appreciate the functionality of this card and would love to help reproduce this and provide any logs you need.
Sincerely, let's try again and try to solve this together. Thanks.

**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
Card Version: 1.0.5
Home Assistant Core: 2023.9

**Last working release (if known):**
Card Version: 1.0.5
Home Assistant Core: 2023.8.4

**Browser and Operating System:**
Windows, Edge, Chrome + Android, Home Assistant Mobile App

**Description of problem:**
In Home Assistant Core 2023.9, a new weather forecast scheme was introduced in which entities no longer have forecast attributes, and instead forecast data must be retrieved by calling a service (weather.get_forecast) ([Ref](https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service)). This card does not call the service, and therefore entities without forecast attributes do not appear in this card.

**Javascript errors shown in the web inspector (if applicable):**
```
platinum-weather-card-df6d26e2.js:41  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')
    at ge._getForecastPropFromWeather (platinum-weather-card-df6d26e2.js:268:71)
    at ge._checkForErrors (platinum-weather-card-df6d26e2.js:73:17788)
    at ge.render (platinum-weather-card-df6d26e2.js:268:1014)
    at ge.update (platinum-weather-card-df6d26e2.js:47:547)
    at ge.performUpdate (platinum-weather-card-df6d26e2.js:41:5079)
    at ge.scheduleUpdate (platinum-weather-card-df6d26e2.js:41:4726)
    at ge._$EC (platinum-weather-card-df6d26e2.js:41:4634)
```

**Comment by tommyjlong** [comment]
I too would love to see this card support the new forecast subscription methods! :)

I have a custom weather integration that I have been re-doing to support this new method, so would luv to have this card support it as I currently use this card with my current custom weather integration.

I don't know javascript, but I have been looking at the [hui-weather-forecast card](https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/cards/hui-weather-forecast-card.ts) to maybe see what it has done to support the new method.

**Comment by DavidFW1960** [comment]
I'm sure Simon will get to this in due course. His real time job is taking all his time at the moment and then some. It's worth noting it's only recently the card was amended to even allow you to use weather entities.
I'd suggest for the time being using template sensors to extract the data from the weather entity and configuring the card for those sensors. That will work perfectly.

**Comment by Scoop2389** [comment]
That's totally fine, and I respect his work and hope he gets a chance to work on it whenever he can.

**Comment by MadMacMad** [comment]
well... to be honest... 
don't think we see a update soon...
i'll already heard he is busy last 2 years...
i'll personally moved to another... 
this card doesn't work with:
Openweathermap
DWD
or any other that followed the standard and updated.

**Comment by DaN66O** [comment]
> i'll personally moved to another...

Which other card supports forecast ?

**Comment by kaijk** [comment]
As long as I can supply my own sensor data for all the fields, I'm OK. I get data from the Openweather REST API and roll my own sensors.

**Comment by Scoop2389** [comment]
Yeah, the only thing that doesn't work is the forecast

**Comment by Tillsy** [comment]
Is there anyone that could fork this project and take it over?

**Comment by dugite-code** [comment]
@Tillsy there are several forks already that appear to be doing their own thing with this card. [this one](https://github.com/tommyjlong/platinum-weather-card) appears to have some good explanations throughout the readme regarding the differences needed to make it work. Disclaimer I haven't tried any of the forks myself.

**Comment by tommyjlong** [comment]
>  [this one](https://github.com/tommyjlong/platinum-weather-card) appears to have some good explanations throughout the readme regarding the differences needed to make it work. Disclaimer I haven't tried any of the forks myself.

Although I don't program in Javascript, nor Typescript,  I did manage to figure out how to get the new HA method for forecast data working on this card, plus a couple of other things here and there.  Its working for my purposes, and its possible I may have broke other things along the way, but I don't plan on maintaining it.  

Anyway, anyone is welcome to take a look at it for reference (or even use it).  I hope Simon gets some free time to get this going again, as this card is really an awesome piece of work 🥇 !!

**Comment by Scoop2389** [comment]
Thanks for your fork! I have just began using it and it is pretty awesome and I haven't come across anything broken yet 😁

**Comment by majkers** [comment]
@tommyjlong can you please share your template sensors form home assistant to make it work? I am still getting errors like:
`'entity_forecast_icon_1=sensor.old_forecast_style_weather' value needs to have a number`

**Comment by Scoop2389** [comment]
I personally moved away from this card in favor for [this fork](https://github.com/tommyjlong/platinum-weather-card) which works with the new format.
